controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    br_wheel_effort_controller:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

br_wheel_effort_controller:
  ros__parameters:
    joints:
      - sus-bar-fright-brwheel
